# Generated by Django 5.0.2 on 2024-06-13 18:11

from django.db import migrations
from django.contrib.auth.models import Group

def  create_user_groups(apps, schema_editor):
    group_names = ['students', 'basics', 'admins', 'legacies']
    for name in group_names:
        Group.objects.create(name=name)
        
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_user_groups)
    ]
