# Generated by Django 5.1.8 on 2025-10-27 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staticpages", "0002_address_footerlinks_contactinfo_footer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="contactInfo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="staticpages.contactinfo",
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="quickLinks",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="staticpages.footerlinks",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
