from django.urls import path
from . import views

urlpatterns = [ 
    path('', views.admin_home, name='admin_home'),
#     path('products/', views.product_list, name='product_list'),
#     path('products/add/', views.product_create, name='product_create'),
#     path('products/<int:pk>/', views.product_update, name='product_update'),
#     path('products/<int:pk>/delete/', views.product_delete, name='product_delete'),
#     path('orders/', views.order_list, name='order_list'),
#     path('orders/<int:pk>/', views.order_update, name='order_update'),
#     path('orders/<int:pk>/delete/', views.order_delete, name='order_delete'),
#     path('payments/', views.payment_list, name='payment_list'),
#     path('payments/<int:pk>/', views.payment_update, name='payment_update'),
#     path('payments/<int:pk>/delete/', views.payment_delete, name='payment_delete'),
#     path('users/', views.user_list, name='user_list'),
#     path('users/<int:pk>/', views.user_update, name='user_update'),
#     path('users/<int:pk>/delete/', views.user_delete, name='user_delete'),
#     path('users/<int:pk>/password/', views.user_password, name='user_password'),
#     path('users/<int:pk>/profile/', views.user_profile, name='user_profile'),
#     path('users/<int:pk>/profile/edit/', views.user_profile_edit, name='user_profile_edit'),
#     path('users/<int:pk>/profile/delete/', views.user_profile_delete, name='user_profile_delete'),
#     path('users/<int:pk>/profile/password/', views.user_profile_password, name='user_profile_password'),
#     path('users/<int:pk>/profile/orders/', views.user_profile_orders, name='user_profile_orders'),
#     path('users/<int:pk>/profile/orders/<int:pk>/', views.user_profile_order_details, name='user_profile_order_details'),
#     path('users/<int:pk>/profile/products/', views.user_profile_products, name='user_profile_products'),
#     path('users/<int:pk>/profile/products/<int:pk>/', views.user_profile_product_details, name='user_profile_product_details'),
#     path('users/<int:pk>/profile/products/<int:pk>/edit/', views.user_profile_product_edit, name='user_profile_product_edit'),
#     path('users/<int:pk>/profile/products/<int:pk>/delete/', views.user_profile_product_delete, name='user_profile_product_delete'),
#     path('users/<int:pk>/profile/products/add/', views.user_profile_product_add, name='user_profile_product_add'),
#     path('users/<int:pk>/profile/products/add/images/', views.user_profile_product_add_images, name='user_profile_product_add_images'),
#     path('users/<int:pk>/profile/products/add/images/delete/', views.user_profile_product_add_images_delete, name='user_profile_product_add_images_delete'),
#     path('users/<int:pk>/profile/products/add/images/edit/', views.user_profile_product_add_images_edit, name='user_profile_product_add_images_edit'),
#     path('users/<int:pk>/profile/products/add/images/edit/delete/', views.user_profile_product_add_images_edit_delete, name='user_profile_product_add_images_edit_delete'),
#     path('users/<int:pk>/profile/products/add/images/edit/add/', views.user_profile_product_add_images_edit_add, name='user_profile_product_add_images_edit_add'),
#     path('users/<int:pk>/profile/products/add/images/edit/add/images/', views.user_profile_product_add_images_edit_add_images, name='user_profile_product_add_images_edit_add_images'),
#     path('users/<int:pk>/profile/products/add/images/edit/add/images/delete/', views.user_profile_product_add_images_edit_add_images_delete, name='user_profile_product_add_images_edit_add_images_delete'),
#     path('users/<int:pk>/profile/products/add/images/edit/add/images/edit/', views.user_profile_product_add_images_edit_add_images_edit, name='user_profile_product_add_images_edit_add_images_edit'),
#     path('users/<int:pk>/profile/products/add/images/edit/add/images/edit/delete/', views.user_profile_product_add_images_edit_add_images_edit_delete, name='user_profile_product_add_images_edit_add_images_edit_delete'),
]