# Generated by Django 5.1.7 on 2025-05-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='two_factor_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='two_factor_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
