# Generated by Django 5.1.1 on 2024-09-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account_reference",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="transaction",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_desc",
            field=models.CharField(default="", max_length=255),
        ),
    ]
