# Generated by Django 5.0.9 on 2024-11-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_created_at_transaction_timestamp'),
        ('payment', '0002_transaction_account_reference_and_more'),
    ]

    operations = [
    ]
