# Generated by Django 5.1.7 on 2025-06-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='auto_now',
            new_name='created_at',
        ),
    ]
