# Generated by Django 5.0.1 on 2024-01-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_user_student_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='student',
        ),
    ]
