# Generated by Django 5.1.1 on 2024-09-30 09:32

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cart",
            name="slug",
            field=models.SlugField(),
        ),
    ]
