# Generated by Django 5.0 on 2024-12-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_is_students_customuser_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_basic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_legacy',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('basic', 'Basic'), ('legacy', 'Legacy'), ('admin', 'Admin'), ('premium', 'Premium')], default='basic', max_length=10),
        ),
    ]
