# Generated by Django 5.1.1 on 2024-09-30 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_alter_review_unique_together_cart_slug"),
        ("products", "0002_alter_product_student"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("product", "reviewer")},
        ),
    ]
