# Generated by Django 5.1.7 on 2025-06-02 04:09

from django.db import migrations
from django.conf import settings


def create_wishlists_for_existing_users(apps, schema_editor):
    """Create wishlists for existing users who don't have one."""
    User = apps.get_model(settings.AUTH_USER_MODEL)
    WishList = apps.get_model('marketplace', 'WishList')

    # Get all users who don't have a wishlist
    users_without_wishlist = User.objects.filter(wishlist__isnull=True)

    # Create wishlists for these users
    wishlists_to_create = []
    for user in users_without_wishlist:
        wishlists_to_create.append(WishList(user=user))

    # Bulk create for efficiency
    if wishlists_to_create:
        WishList.objects.bulk_create(wishlists_to_create)


def reverse_create_wishlists(apps, schema_editor):
    """Reverse migration - this is a no-op since we don't want to delete wishlists."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rename_auto_now_wishlist_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            create_wishlists_for_existing_users,
            reverse_create_wishlists,
        ),
    ]
