# Generated by Django 5.1.8 on 2025-10-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_remove_customuser_is_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
