# Generated by Django 5.1.8 on 2025-10-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_remove_student_user_remove_userprofile_user_and_more"),
        ("products", "0003_alter_product_student"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
