# Generated by Django 5.0.9 on 2024-11-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_update_reaction_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='student',
            name='two_factor_secret',
        ),
        migrations.RemoveField(
            model_name='student',
            name='two_factor_verified',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='marketplace.message'),
        ),
    ]
