# Generated by Django 5.0.2 on 2024-06-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'PROCESSING'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED'), ('canceled', 'CANCELED'), ('refunded', 'REFUNDED'), ('returned', 'RETURNED'), ('pending', 'PENDING')], default='pending', max_length=30),
        ),
    ]
