# Generated by Django 5.1.8 on 2025-10-27 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_price"),
        ("users", "0002_remove_student_email_remove_student_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="users.student",
            ),
        ),
    ]
