# Generated by Django 5.1.15 on 2026-02-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="course_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="edition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="exchange_option",
            field=models.CharField(
                blank=True,
                choices=[("sell", "Sell"), ("exchange", "Exchange"), ("both", "Both")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="isbn",
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
