# Generated by Django 5.0.2 on 2024-03-20 13:25

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=products.models.default_category, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
    ]
