# Generated by Django 5.0.2 on 2024-04-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_cart_cartitem_cart_items'),
        ('products', '0006_alter_image_image_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.student'),
        ),
    ]
