# Generated by Django 5.0.2 on 2024-06-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
